parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'
  
env:
  es6: true
  browser: true
  commonjs: true

extends: 'htmlacademy/es6'

rules:
  'no-unused-expressions':
    - error
    - allowShortCircuit: true